# Generated by Django 4.2.15 on 2025-03-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('function_lib', '0002_functionlib_is_active_functionlib_permission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionlib',
            name='function_type',
            field=models.CharField(choices=[('INTERNAL', '内置'), ('PUBLIC', '公开')],
                                   default='PUBLIC', max_length=20, verbose_name='函数类型'),
        ),
        migrations.AddField(
            model_name='functionlib',
            name='icon',
            field=models.CharField(default='/ui/favicon.ico', max_length=256,
                                   verbose_name='函数库icon'),
        ),
        migrations.AddField(
            model_name='functionlib',
            name='init_field_list',
            field=models.JSONField(default=list, verbose_name='启动字段列表'),
        ),
        migrations.AddField(
            model_name='functionlib',
            name='init_params',
            field=models.CharField(max_length=102400, null=True, verbose_name='初始化参数'),
        ),
        migrations.AddField(
            model_name='functionlib',
            name='template_id',
            field=models.UUIDField(default=None, null=True, verbose_name='模版id'),
        ),
    ]
